# Generated by Django 5.2.14 on 2026-05-14 22:34

import apps.inspecoes.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edificacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(max_length=200, verbose_name='Localização')),
                ('sub_localizacao', models.CharField(blank=True, max_length=200, verbose_name='Sub-localização')),
                ('verificacao', models.CharField(max_length=300, verbose_name='Verificação')),
                ('grupo_tecnico', models.CharField(choices=[('esquadrias', 'Esquadrias'), ('instalacoes', 'Instalações Hidrossanitárias'), ('acabamento', 'Acabamento'), ('instalacoes_mecanicas', 'Instalações Mecânicas'), ('instalacoes_eletricas', 'Instalações Elétricas'), ('estrutura', 'Estrutura'), ('impermeabilizacao', 'Impermeabilização'), ('cobertura', 'Cobertura'), ('equipamentos', 'Equipamentos Prediais'), ('acessibilidade', 'Acessibilidade'), ('outros', 'Outros')], max_length=50, verbose_name='Grupo técnico')),
                ('descricao_nao_conformidade', models.TextField(verbose_name='Descrição da não conformidade')),
                ('requisito_afetado', models.CharField(choices=[('seguranca_estrutural', 'Segurança Estrutural'), ('acessibilidade', 'Acessibilidade'), ('saude_qualidade_ar', 'Saúde e Qualidade do Ar'), ('funcionalidade', 'Funcionalidade'), ('estetica', 'Estética'), ('eficiencia_energetica', 'Eficiência Energética'), ('sustentabilidade', 'Sustentabilidade'), ('durabilidade', 'Durabilidade')], max_length=50, verbose_name='Requisito afetado')),
                ('gravidade', models.IntegerField(verbose_name='Gravidade (G)')),
                ('urgencia', models.IntegerField(verbose_name='Urgência (U)')),
                ('tendencia', models.IntegerField(verbose_name='Tendência (T)')),
                ('gut_total', models.IntegerField(default=0, editable=False, verbose_name='Índice GUT')),
                ('prioridade_risco', models.IntegerField(choices=[(1, 'Prioridade 1 — Crítico'), (2, 'Prioridade 2 — Regular'), (3, 'Prioridade 3 — Mínimo')], verbose_name='Análise de risco')),
                ('recomendacao', models.TextField(verbose_name='Recomendação técnica')),
                ('direcionamento', models.CharField(choices=[('garantia', 'Garantia de obra'), ('manutencao', 'Manutenção'), ('nova_contratacao', 'Nova contratação')], max_length=30, verbose_name='Direcionamento')),
                ('prazo_meses', models.IntegerField(choices=[(1, '1 mês'), (3, '3 meses'), (6, '6 meses'), (12, '12 meses'), (18, '18 meses'), (24, '24 meses')], verbose_name='Prazo para resolução')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Achado',
                'verbose_name_plural': 'Achados',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ImageField(upload_to=apps.inspecoes.models.foto_upload_path, verbose_name='Foto')),
                ('nome_original', models.CharField(max_length=255)),
                ('tamanho_bytes', models.IntegerField(default=0)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('achado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='inspecoes.achado', verbose_name='Achado')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'ordering': ['data_upload'],
            },
        ),
        migrations.CreateModel(
            name='Inspecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profissional', models.CharField(max_length=200, verbose_name='Profissional responsável')),
                ('especialidade', models.CharField(choices=[('civil', 'Civil'), ('mecanica', 'Mecânica'), ('eletrica', 'Elétrica')], max_length=20, verbose_name='Especialidade')),
                ('data_inspecao', models.DateField(verbose_name='Data da inspeção')),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('finalizada', 'Finalizada')], default='em_andamento', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('edificacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspecoes', to='edificacoes.edificacao', verbose_name='Edificação')),
            ],
            options={
                'verbose_name': 'Inspeção',
                'verbose_name_plural': 'Inspeções',
                'ordering': ['-data_inspecao'],
            },
        ),
        migrations.AddField(
            model_name='achado',
            name='inspecao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achados', to='inspecoes.inspecao', verbose_name='Inspeção'),
        ),
    ]
