# Generated by Django 5.2.14 on 2026-05-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecoes', '0002_opcaocampo'),
    ]

    operations = [
        migrations.AddField(
            model_name='achado',
            name='em_conformidade',
            field=models.BooleanField(default=False, help_text='Marque quando o item verificado estiver conforme. Os campos GUT ficam desabilitados.', verbose_name='Em conformidade'),
        ),
        migrations.AlterField(
            model_name='achado',
            name='descricao_nao_conformidade',
            field=models.TextField(blank=True, verbose_name='Descrição da não conformidade'),
        ),
        migrations.AlterField(
            model_name='achado',
            name='direcionamento',
            field=models.CharField(choices=[('garantia', 'Garantia de obra'), ('manutencao', 'Manutenção'), ('nova_contratacao', 'Nova contratação')], default='manutencao', max_length=30, verbose_name='Direcionamento'),
        ),
        migrations.AlterField(
            model_name='achado',
            name='gravidade',
            field=models.IntegerField(default=1, verbose_name='Gravidade (G)'),
        ),
        migrations.AlterField(
            model_name='achado',
            name='prazo_meses',
            field=models.IntegerField(choices=[(1, '1 mês'), (3, '3 meses'), (6, '6 meses'), (12, '12 meses'), (18, '18 meses'), (24, '24 meses')], default=12, verbose_name='Prazo para resolução'),
        ),
        migrations.AlterField(
            model_name='achado',
            name='prioridade_risco',
            field=models.IntegerField(choices=[(1, 'Prioridade 1 — Crítico'), (2, 'Prioridade 2 — Regular'), (3, 'Prioridade 3 — Mínimo')], default=3, verbose_name='Análise de risco'),
        ),
        migrations.AlterField(
            model_name='achado',
            name='recomendacao',
            field=models.TextField(blank=True, verbose_name='Recomendação técnica'),
        ),
        migrations.AlterField(
            model_name='achado',
            name='tendencia',
            field=models.IntegerField(default=1, verbose_name='Tendência (T)'),
        ),
        migrations.AlterField(
            model_name='achado',
            name='urgencia',
            field=models.IntegerField(default=1, verbose_name='Urgência (U)'),
        ),
    ]
