# Generated by Django 5.2.14 on 2026-05-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecoes', '0004_inspecaoespecialidade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspecao',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Inspeção', 'verbose_name_plural': 'Inspeções'},
        ),
        migrations.AlterField(
            model_name='achado',
            name='grupo_tecnico',
            field=models.CharField(max_length=200, verbose_name='Grupo técnico'),
        ),
        migrations.AlterField(
            model_name='achado',
            name='requisito_afetado',
            field=models.CharField(max_length=200, verbose_name='Requisito afetado'),
        ),
    ]
