# Generated by Django 5.2.14 on 2026-06-08 13:40

import apps.inspecoes.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificacoes', '0001_initial'),
        ('inspecoes', '0006_logacesso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='logacesso',
            name='tipo',
            field=models.CharField(choices=[('login', 'Login'), ('inspecao_criada', 'Inspeção criada'), ('inspecao_excluida', 'Inspeção excluída'), ('especialidade_criada', 'Especialidade criada'), ('especialidade_excluida', 'Especialidade excluída'), ('achado_criado', 'Achado criado'), ('achado_excluido', 'Achado excluído'), ('visita_criada', 'Visita técnica criada'), ('visita_excluida', 'Visita técnica excluída')], max_length=30, verbose_name='Evento'),
        ),
        migrations.CreateModel(
            name='VisitaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_visita', models.DateField(verbose_name='Data da visita')),
                ('responsavel', models.CharField(max_length=200, verbose_name='Profissional responsável')),
                ('motivo', models.TextField(verbose_name='Motivo da visita')),
                ('achados', models.TextField(blank=True, verbose_name='Achados da visita')),
                ('conclusoes_encaminhamentos', models.TextField(blank=True, verbose_name='Conclusões e encaminhamentos')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('edificacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitas', to='edificacoes.edificacao', verbose_name='Localidade')),
            ],
            options={
                'verbose_name': 'Visita técnica',
                'verbose_name_plural': 'Visitas técnicas',
                'ordering': ['-data_visita', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='VisitaFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ImageField(upload_to=apps.inspecoes.models.visita_foto_upload_path, verbose_name='Foto')),
                ('nome_original', models.CharField(max_length=255)),
                ('tamanho_bytes', models.IntegerField(default=0)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='inspecoes.visitatecnica', verbose_name='Visita')),
            ],
            options={
                'verbose_name': 'Foto de visita',
                'verbose_name_plural': 'Fotos de visita',
                'ordering': ['data_upload'],
            },
        ),
    ]
