# Generated by Django 5.2.14 on 2026-06-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecoes', '0009_visita_disciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspecaoespecialidade',
            name='profissional',
            field=models.TextField(help_text='Um nome por linha.', verbose_name='Profissionais responsáveis'),
        ),
    ]
