# Generated by Django 5.2.14 on 2026-06-15 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecoes', '0010_alter_inspecaoespecialidade_profissional'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitatecnica',
            name='concluida',
            field=models.BooleanField(default=False, verbose_name='Concluída'),
        ),
        migrations.AddField(
            model_name='visitatecnica',
            name='concluida_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Concluída em'),
        ),
        migrations.AddField(
            model_name='visitatecnica',
            name='visita_pai',
            field=models.ForeignKey(blank=True, help_text='Preenchido quando esta é uma subvisita de acompanhamento.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subvisitas', to='inspecoes.visitatecnica', verbose_name='Visita de origem'),
        ),
        migrations.AlterField(
            model_name='logacesso',
            name='tipo',
            field=models.CharField(choices=[('login', 'Login'), ('inspecao_criada', 'Inspeção criada'), ('inspecao_excluida', 'Inspeção excluída'), ('especialidade_criada', 'Especialidade criada'), ('especialidade_excluida', 'Especialidade excluída'), ('achado_criado', 'Achado criado'), ('achado_excluido', 'Achado excluído'), ('visita_criada', 'Visita técnica criada'), ('visita_excluida', 'Visita técnica excluída'), ('visita_concluida', 'Visita técnica concluída'), ('visita_reaberta', 'Visita técnica reaberta'), ('subvisita_criada', 'Subvisita de acompanhamento criada')], max_length=30, verbose_name='Evento'),
        ),
    ]
