# Generated by Django 5.2.14 on 2026-06-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecoes', '0011_visitatecnica_concluida_visitatecnica_concluida_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achado',
            name='ordem_servico',
            field=models.CharField(blank=True, help_text='Número da OS aberta no sistema Resolve. Preencher quando direcionamento for Manutenção.', max_length=50, verbose_name='Ordem de serviço (Resolve)'),
        ),
    ]
