# Generated by Django 5.2.14 on 2026-06-18 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspecoes', '0012_achado_ordem_servico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achado',
            name='ordem_servico',
        ),
    ]
