# Generated by Django 5.2.14 on 2026-06-18 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecoes', '0013_remove_achado_ordem_servico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='achado',
            name='ordem_servico',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número da OS (Resolve)'),
        ),
        migrations.AddField(
            model_name='achado',
            name='os_data_abertura',
            field=models.DateField(blank=True, null=True, verbose_name='Data de abertura da OS'),
        ),
        migrations.AddField(
            model_name='achado',
            name='os_observacoes',
            field=models.TextField(blank=True, verbose_name='Observações complementares'),
        ),
        migrations.AddField(
            model_name='achado',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('finalizado', 'Finalizado')], default='pendente', max_length=20, verbose_name='Status do acompanhamento'),
        ),
        migrations.AlterField(
            model_name='logacesso',
            name='tipo',
            field=models.CharField(choices=[('login', 'Login'), ('inspecao_criada', 'Inspeção criada'), ('inspecao_excluida', 'Inspeção excluída'), ('especialidade_criada', 'Especialidade criada'), ('especialidade_excluida', 'Especialidade excluída'), ('achado_criado', 'Achado criado'), ('achado_excluido', 'Achado excluído'), ('achado_reclassificado', 'Achado reclassificado'), ('achado_acompanhamento', 'Acompanhamento de achado atualizado'), ('visita_criada', 'Visita técnica criada'), ('visita_excluida', 'Visita técnica excluída'), ('visita_concluida', 'Visita técnica concluída'), ('visita_reaberta', 'Visita técnica reaberta'), ('subvisita_criada', 'Subvisita de acompanhamento criada')], max_length=30, verbose_name='Evento'),
        ),
        migrations.CreateModel(
            name='EncaminhamentoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de_direcionamento', models.CharField(choices=[('garantia', 'Garantia de obra'), ('manutencao', 'Manutenção'), ('nova_contratacao', 'Nova contratação')], max_length=30, verbose_name='Categoria anterior')),
                ('para_direcionamento', models.CharField(choices=[('garantia', 'Garantia de obra'), ('manutencao', 'Manutenção'), ('nova_contratacao', 'Nova contratação')], max_length=30, verbose_name='Nova categoria')),
                ('justificativa', models.TextField(verbose_name='Justificativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data/hora')),
                ('achado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_encaminhamento', to='inspecoes.achado', verbose_name='Achado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclassificacoes', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Histórico de encaminhamento',
                'verbose_name_plural': 'Históricos de encaminhamento',
                'ordering': ['-criado_em'],
            },
        ),
    ]
