# Generated by Django 5.2.14 on 2026-09-10 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecoes', '0014_acompanhamento_achados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inspecaoespecialidade',
            name='unique_inspecao_especialidade',
        ),
        migrations.RemoveConstraint(
            model_name='opcaocampo',
            name='unique_campo_label',
        ),
        migrations.AddField(
            model_name='achado',
            name='excluido_em',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em'),
        ),
        migrations.AddField(
            model_name='achado',
            name='excluido_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por'),
        ),
        migrations.AddField(
            model_name='foto',
            name='excluido_em',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em'),
        ),
        migrations.AddField(
            model_name='foto',
            name='excluido_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por'),
        ),
        migrations.AddField(
            model_name='inspecao',
            name='excluido_em',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em'),
        ),
        migrations.AddField(
            model_name='inspecao',
            name='excluido_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por'),
        ),
        migrations.AddField(
            model_name='inspecaoespecialidade',
            name='excluido_em',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em'),
        ),
        migrations.AddField(
            model_name='inspecaoespecialidade',
            name='excluido_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por'),
        ),
        migrations.AddField(
            model_name='opcaocampo',
            name='excluido_em',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em'),
        ),
        migrations.AddField(
            model_name='opcaocampo',
            name='excluido_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por'),
        ),
        migrations.AddField(
            model_name='visitafoto',
            name='excluido_em',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em'),
        ),
        migrations.AddField(
            model_name='visitafoto',
            name='excluido_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por'),
        ),
        migrations.AddField(
            model_name='visitatecnica',
            name='excluido_em',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em'),
        ),
        migrations.AddField(
            model_name='visitatecnica',
            name='excluido_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por'),
        ),
        migrations.AddConstraint(
            model_name='inspecaoespecialidade',
            constraint=models.UniqueConstraint(condition=models.Q(('excluido_em__isnull', True)), fields=('inspecao', 'especialidade'), name='unique_inspecao_especialidade'),
        ),
        migrations.AddConstraint(
            model_name='opcaocampo',
            constraint=models.UniqueConstraint(condition=models.Q(('excluido_em__isnull', True)), fields=('campo', 'label'), name='unique_campo_label'),
        ),
    ]
