# Generated by Django 5.2.14 on 2026-10-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecoes', '0015_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspecaoespecialidade',
            name='conclusao',
            field=models.TextField(blank=True, help_text='Texto livre, redigido pelo profissional responsável — exigido para finalizar esta especialidade.', verbose_name='Conclusão e direcionamentos'),
        ),
    ]
