# Generated by Django 5.2.14 on 2026-10-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecoes', '0016_inspecaoespecialidade_conclusao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logacesso',
            name='tipo',
            field=models.CharField(choices=[('login', 'Login'), ('inspecao_criada', 'Inspeção criada'), ('inspecao_excluida', 'Inspeção excluída'), ('especialidade_criada', 'Especialidade criada'), ('especialidade_excluida', 'Especialidade excluída'), ('achado_criado', 'Achado criado'), ('achado_excluido', 'Achado excluído'), ('achado_reclassificado', 'Achado reclassificado'), ('achado_acompanhamento', 'Acompanhamento de achado atualizado'), ('visita_criada', 'Visita técnica criada'), ('visita_excluida', 'Visita técnica excluída'), ('visita_concluida', 'Visita técnica concluída'), ('visita_reaberta', 'Visita técnica reaberta'), ('subvisita_criada', 'Subvisita de acompanhamento criada'), ('relatorio_final_gerado', 'Relatório Final de Inspeção gerado')], max_length=30, verbose_name='Evento'),
        ),
    ]
