# Generated by Django 5.2.14 on 2026-10-07 13:11

import apps.inspecoes.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecoes', '0017_logacesso_tipo_relatorio_final'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioFinalInspecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_versao', models.PositiveIntegerField(verbose_name='Versão')),
                ('arquivo_pdf', models.FileField(upload_to=apps.inspecoes.models.relatorio_pdf_upload_path, verbose_name='PDF gerado')),
                ('snapshot', models.JSONField(verbose_name='Snapshot')),
                ('gerado_em', models.DateTimeField(auto_now_add=True, verbose_name='Gerado em')),
                ('gerado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relatorios_finais_gerados', to=settings.AUTH_USER_MODEL, verbose_name='Gerado por')),
                ('inspecao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relatorios_finais', to='inspecoes.inspecao', verbose_name='Inspeção')),
            ],
            options={
                'verbose_name': 'Relatório Final de Inspeção',
                'verbose_name_plural': 'Relatórios Finais de Inspeção',
                'ordering': ['-numero_versao'],
                'constraints': [models.UniqueConstraint(fields=('inspecao', 'numero_versao'), name='unique_versao_por_inspecao')],
            },
        ),
    ]
