# Generated by Django 5.2.14 on 2026-08-18 18:34

from django.db import migrations, models


def atribuir_siglas_conhecidas(apps, schema_editor):
    Edificacao = apps.get_model('edificacoes', 'Edificacao')
    mapeamento = {
        'Sede MPDFT — Bloco A': 'BSBI',
        'Promotoria de Justiça da Defesa da Infância e Juventude': 'PJIJ',
    }
    for nome, sigla in mapeamento.items():
        Edificacao.objects.filter(nome=nome).update(sigla=sigla)


def reverter_siglas(apps, schema_editor):
    Edificacao = apps.get_model('edificacoes', 'Edificacao')
    Edificacao.objects.filter(sigla__in=['BSBI', 'PJIJ']).update(sigla=None)


class Migration(migrations.Migration):

    dependencies = [
        ('edificacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificacao',
            name='sigla',
            field=models.CharField('Sigla', max_length=10, unique=True, null=True, blank=True),
        ),
        migrations.RunPython(atribuir_siglas_conhecidas, reverter_siglas),
    ]
