# Generated by Django 5.2.14 on 2026-09-10 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificacoes', '0002_edificacao_sigla'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='edificacao',
            name='excluido_em',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em'),
        ),
        migrations.AddField(
            model_name='edificacao',
            name='excluido_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por'),
        ),
        migrations.AlterField(
            model_name='edificacao',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='edificacao',
            name='sigla',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Sigla'),
        ),
        migrations.AddConstraint(
            model_name='edificacao',
            constraint=models.UniqueConstraint(condition=models.Q(('excluido_em__isnull', True)), fields=('nome',), name='unique_edificacao_nome_ativa'),
        ),
        migrations.AddConstraint(
            model_name='edificacao',
            constraint=models.UniqueConstraint(condition=models.Q(('excluido_em__isnull', True)), fields=('sigla',), name='unique_edificacao_sigla_ativa'),
        ),
    ]
