# Generated by Django 5.2.14 on 2026-10-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificacoes', '0003_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificacao',
            name='descritivo',
            field=models.TextField(blank=True, help_text='Idade, tipo construtivo, uso etc. — reutilizado em todo Relatório Final de Inspeção desta edificação.', verbose_name='Descritivo'),
        ),
    ]
