# Generated by Django 5.2.14 on 2026-08-18 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edificacoes', '0002_edificacao_sigla'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterioAcessibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, unique=True, verbose_name='Critério')),
                ('base_legal', models.TextField(blank=True, verbose_name='Base legal')),
            ],
            options={
                'verbose_name': 'Critério de acessibilidade',
                'verbose_name_plural': 'Critérios de acessibilidade',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OK', 'OK'), ('PENDENTE', 'Pendente'), ('NAO_SE_APLICA', 'Não se aplica')], max_length=20, verbose_name='Status')),
                ('resolucao_diagnostico', models.CharField(blank=True, max_length=40, verbose_name='Resolução (diagnóstico)')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('status_acao', models.CharField(choices=[('NAO_INICIADA', 'Não iniciada'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída')], default='NAO_INICIADA', max_length=20, verbose_name='Status da ação')),
                ('responsavel', models.CharField(blank=True, max_length=200, verbose_name='Responsável')),
                ('prazo', models.DateField(blank=True, null=True, verbose_name='Prazo')),
                ('resolucao_prevista', models.CharField(blank=True, max_length=40, verbose_name='Resolução prevista')),
                ('ordem_servico', models.CharField(blank=True, max_length=100, verbose_name='Ordem de serviço')),
                ('data_os', models.DateField(blank=True, null=True, verbose_name='Data da OS')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('atualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes', to='acessibilidade.criterioacessibilidade')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_anterior', models.JSONField(verbose_name='Estado anterior')),
                ('snapshot_novo', models.JSONField(verbose_name='Estado novo')),
                ('editado_em', models.DateTimeField(auto_now_add=True, verbose_name='Editado em')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='acessibilidade.avaliacao')),
                ('editado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Editado por')),
            ],
            options={
                'verbose_name': 'Histórico de avaliação',
                'verbose_name_plural': 'Histórico de avaliações',
                'ordering': ['-editado_em'],
            },
        ),
        migrations.CreateModel(
            name='LocalAcessibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiao', models.CharField(choices=[('AREA PÚBLICA', 'Área pública'), ('ÁREA PÚBLICA', 'Área pública (grafia alternativa)'), ('AUDITORIO E RESTAURANTE', 'Auditório e restaurante'), ('INTERIOR DO LOTE - DESCOBERTO', 'Interior do lote - descoberto'), ('MEZANINO', 'Mezanino'), ('PAVIMENTO 01', 'Pavimento 01'), ('PAVIMENTO 02', 'Pavimento 02'), ('PAVIMENTO TIPO', 'Pavimento tipo'), ('SUBSOLO', 'Subsolo'), ('SUBSOLO 01', 'Subsolo 01'), ('SUBSOLO 02', 'Subsolo 02'), ('SUBSOLO 1', 'Subsolo 1'), ('SUBSOLO 2', 'Subsolo 2'), ('SUBSOLO 3', 'Subsolo 3'), ('TODOS OS PAVIMENTOS', 'Todos os pavimentos'), ('TODOS PAVIMENTOS', 'Todos pavimentos'), ('TÉRREO', 'Térreo'), ('VÁRIOS PAVIMENTOS', 'Vários pavimentos')], max_length=40, verbose_name='Região')),
                ('nome', models.CharField(max_length=200, verbose_name='Local')),
                ('edificacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locais_acessibilidade', to='edificacoes.edificacao', verbose_name='Edificação')),
            ],
            options={
                'verbose_name': 'Local de acessibilidade',
                'verbose_name_plural': 'Locais de acessibilidade',
                'ordering': ['edificacao__nome', 'regiao', 'nome'],
                'unique_together': {('edificacao', 'regiao', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes', to='acessibilidade.localacessibilidade'),
        ),
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together={('local', 'criterio')},
        ),
    ]
