# Generated by Django 5.2.14 on 2026-09-10 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessibilidade', '0001_initial'),
        ('edificacoes', '0003_soft_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='localacessibilidade',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='excluido_em',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='excluido_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por'),
        ),
        migrations.AddField(
            model_name='criterioacessibilidade',
            name='excluido_em',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em'),
        ),
        migrations.AddField(
            model_name='criterioacessibilidade',
            name='excluido_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por'),
        ),
        migrations.AddField(
            model_name='localacessibilidade',
            name='excluido_em',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em'),
        ),
        migrations.AddField(
            model_name='localacessibilidade',
            name='excluido_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por'),
        ),
        migrations.AlterField(
            model_name='criterioacessibilidade',
            name='nome',
            field=models.CharField(max_length=300, verbose_name='Critério'),
        ),
        migrations.AddConstraint(
            model_name='avaliacao',
            constraint=models.UniqueConstraint(condition=models.Q(('excluido_em__isnull', True)), fields=('local', 'criterio'), name='unique_avaliacao_ativa'),
        ),
        migrations.AddConstraint(
            model_name='criterioacessibilidade',
            constraint=models.UniqueConstraint(condition=models.Q(('excluido_em__isnull', True)), fields=('nome',), name='unique_criterio_acessibilidade_ativo'),
        ),
        migrations.AddConstraint(
            model_name='localacessibilidade',
            constraint=models.UniqueConstraint(condition=models.Q(('excluido_em__isnull', True)), fields=('edificacao', 'regiao', 'nome'), name='unique_local_acessibilidade_ativo'),
        ),
    ]
