# Generated by Django 5.2.14 on 2026-05-21 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecoes', '0005_achado_grupo_requisito_sem_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('login', 'Login'), ('inspecao_criada', 'Inspeção criada'), ('inspecao_excluida', 'Inspeção excluída'), ('especialidade_criada', 'Especialidade criada'), ('especialidade_excluida', 'Especialidade excluída'), ('achado_criado', 'Achado criado'), ('achado_excluido', 'Achado excluído')], max_length=30, verbose_name='Evento')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data/hora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_acesso', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de acesso',
                'verbose_name_plural': 'Logs de acesso',
                'ordering': ['-criado_em'],
            },
        ),
    ]
